export type EnglishMoment = {
  english: string
  chinese: string
}

export const moments: EnglishMoment[] = [
  { english: 'Every new word opens a new window.', chinese: '每一个新单词，都会打开一扇新的窗。' },
  { english: 'Stay curious, and the world stays interesting.', chinese: '保持好奇，世界便始终有趣。' },
  { english: 'Small steps can take you surprisingly far.', chinese: '小小的脚步，也能带你走得很远。' },
  { english: 'The best stories begin with a little courage.', chinese: '最好的故事，都始于一点勇气。' },
  { english: 'Today is a good day to begin again.', chinese: '今天很适合重新开始。' },
  { english: 'Keep going; your future self is waiting.', chinese: '继续前进，未来的你正在等你。' },
  { english: 'A quiet mind can hear the clearest answers.', chinese: '内心安静时，答案才最清晰。' },
  { english: 'Sometimes the long way home teaches us more.', chinese: '有时，漫长的归途会教会我们更多。' },
  { english: 'Believe in the person you are becoming.', chinese: '相信那个正在成长的自己。' },
  { english: 'One brave choice can change the whole scene.', chinese: '一个勇敢的选择，就能改变整个局面。' },
  { english: 'You do not need perfect timing to start.', chinese: '开始并不需要一个完美的时机。' },
  { english: 'Let the hard days make you stronger, not smaller.', chinese: '让艰难的日子使你强大，而不是退缩。' },
  { english: 'There is always more light beyond the clouds.', chinese: '云层之外，总有更多光亮。' },
  { english: 'Learn slowly, remember deeply.', chinese: '慢慢学习，深深记住。' },
  { english: 'A kind word can change someone’s entire day.', chinese: '一句善意的话，可能改变别人一整天。' },
  { english: 'The road ahead begins beneath your feet.', chinese: '前方的路，就从你的脚下开始。' },
  { english: 'Make room for the life you truly want.', chinese: '为你真正想要的生活留出空间。' },
  { english: 'Good things grow when you give them time.', chinese: '美好的事物，需要时间才能生长。' },
  { english: 'Your voice matters, even when it shakes.', chinese: '即使声音颤抖，你的表达依然重要。' },
  { english: 'Practice turns the unfamiliar into the familiar.', chinese: '练习会让陌生逐渐变得熟悉。' },
  { english: 'Do one thing today that tomorrow will thank you for.', chinese: '今天做一件会让明天的自己感谢你的事。' },
  { english: 'The next chapter does not have to repeat the last.', chinese: '下一章不必重复上一章。' },
  { english: 'Be patient with the progress no one else can see.', chinese: '耐心对待那些别人看不见的进步。' },
  { english: 'You are closer than you were yesterday.', chinese: '你已经比昨天更接近目标。' },
  { english: 'Even a slow sunrise still lights the sky.', chinese: '即使日出缓慢，也终会照亮天空。' },
  { english: 'Choose the direction that makes you feel alive.', chinese: '选择那个让你感到充满生命力的方向。' },
  { english: 'Confidence grows each time you try again.', chinese: '每一次重新尝试，都会增长一分自信。' },
  { english: 'The ordinary day may hold an extraordinary moment.', chinese: '平凡的一天，也可能藏着非凡的瞬间。' },
  { english: 'Listen carefully; life often speaks softly.', chinese: '仔细聆听，生活常常轻声诉说。' },
  { english: 'A clear purpose makes a long journey lighter.', chinese: '目标清晰，漫长的旅程也会轻盈一些。' },
  { english: 'You can be both a beginner and a dreamer.', chinese: '你可以既是初学者，也是梦想家。' },
  { english: 'What feels difficult today may feel natural tomorrow.', chinese: '今天觉得困难的事，明天也许会变得自然。' },
  { english: 'Leave a little space for unexpected happiness.', chinese: '给意想不到的幸福留一点空间。' },
  { english: 'The smallest spark can guide you through the dark.', chinese: '最微小的火花，也能引你穿过黑暗。' },
  { english: 'Your pace is valid as long as you keep moving.', chinese: '只要仍在前进，你的步调就值得肯定。' },
  { english: 'Speak the words until they begin to feel like yours.', chinese: '不断说出这些词，直到它们真正属于你。' },
  { english: 'Tomorrow begins with what you practice today.', chinese: '明天，始于你今天的练习。' },
  { english: 'This is not the ending; it is your next beginning.', chinese: '这不是结束，而是你的下一次开始。' },
  { english: 'Strength is built one careful repetition at a time.', chinese: '力量是在一次次认真重复中练成的。' },
  { english: 'Train for the life you want to live.', chinese: '为了你想要的生活而训练。' },
  { english: 'Good form matters more than heavy weight.', chinese: '正确的动作比沉重的重量更重要。' },
  { english: 'Your strongest competition is yesterday’s self.', chinese: '你最强的对手，是昨天的自己。' },
  { english: 'Rest is part of training, not the opposite of it.', chinese: '休息是训练的一部分，而不是训练的反面。' },
  { english: 'Consistency changes the body before motivation notices.', chinese: '在动力察觉之前，坚持已经开始改变身体。' },
  { english: 'Muscle grows when effort meets recovery.', chinese: '努力与恢复相遇时，肌肉才会生长。' },
  { english: 'Food is information as well as energy.', chinese: '食物既是能量，也是身体接收的信息。' },
  { english: 'A sustainable plan is better than a perfect week.', chinese: '可持续的计划，胜过完美的一周。' },
  { english: 'Healthy change is measured in months, not moments.', chinese: '健康的改变以月计算，而不是以瞬间计算。' },
  { english: 'Progress is more than a number on the scale.', chinese: '进步不只是体重秤上的一个数字。' },
  { english: 'Build habits that your future can depend on.', chinese: '培养让未来的自己可以依靠的习惯。' },
  { english: 'Protein supports the work your muscles are doing.', chinese: '蛋白质为肌肉所做的努力提供支持。' },
  { english: 'Balance begins with understanding what you eat.', chinese: '均衡始于了解自己吃下的食物。' },
  { english: 'A thoughtful meal can be a form of self-respect.', chinese: '认真准备一餐，也是尊重自己的一种方式。' },
  { english: 'Your body adapts to the fuel you give it.', chinese: '身体会适应你为它提供的能量。' },
  { english: 'Simple ingredients can create a satisfying meal.', chinese: '简单的食材，也能组成令人满足的一餐。' },
  { english: 'Choose an eating pattern you can follow calmly.', chinese: '选择一种你能从容坚持的饮食方式。' },
  { english: 'Hydration helps every system do its job.', chinese: '充足水分能帮助身体各系统正常运转。' },
  { english: 'Preparation turns a healthy choice into an easy choice.', chinese: '提前准备，会让健康选择变成轻松选择。' },
]
